# SYNTHETIC DATASETS ------
training_data_path: "../training_data" # were the training data will be stored
testing_data_path: "../testing_data" # were a single dataset for testing will be stored
simulation_duration_rec: 240 # how long a single simulated dataset will be
samplerate: 20000 # sampling rate of the simulated and real data

# The following parameters are boundaries for the random generation of the
# simulated data. The actual values will be sampled from a uniform distribution
# between the lower and upper bound. 
num_fish: [1, 10] # how many fish will be simulated 
num_chirps: [10, 30] # how many chirps will be simulated
num_rises: [0, 3] # how many rises will be simulated
noise_stds: [0, 0.01] # standard deviation of the noise
num_electrodes: 11 # how many electrodes will be simulated
eodfs: [300, 1500] # range of the simulated eodfs
chirp_sizes: [20, 150] # range of the simulated chirp sizes in Hz
chirp_durations: [0.005, 0.1] # range of the simulated chirp durations in s
chirp_kurtoses: [0.6, 1.4] # range of the simulated chirp kurtoses (peak shape)
chirp_contrasts: [0.0, 1.0] # range of the simulated chirp contrasts (amplitude trough)
rise_sizes: [10, 100] # range of the simulated rise sizes in Hz
rise_rise_taus: [0.1, 1.5] # range of the simulated rise rise taus in s (how fast the rise starts)
rise_decay_taus: [2, 15] # range of the simulated rise decay taus in s (how fast the rise ends)
# frequency_track_samplerate: 3

# STFT SPECTROGRAM ------
frequency_resolution: 6  # df = fs / nfft
overlap_fraction: 0.99  # hanning window overlap
 
# ROI EXTRACTION ------
time_pad: 0.10 # window size before and after chirp
freq_pad: [-50, 200] # window size below and above the chirp
img_size_px: 128 # size of the extracted image in pixels. The image will must be square

# CNN MODEL ------
num_epochs: 10 # how many epochs to train the model
batch_size: 10 # how many images to train on at once
learning_rate: 0.001 # learning rate of the optimizer
train_size: 0.8 # fraction of the training data to use for training
save_dir: "models/model.pt" # where to save the trained model
plot_dir: "../assets" # where to save the training plots

# TRAINING DATASET ------
generations: 20 # how often to generate a new training dataset and extract chirps

# DETECTOR CONFIGURATION ------
detection_data_path: "../testing_data" # where the testing data will be stored
stride: 0.01 # step size of the detector on the spectrogram in s
min_chirp_dt: 0.04 # minimum time between chirps in s
buffersize: 10 # how large the buffer is in s
spectrogram_overlap: 1 # how much to overlap the spectrograms in the buffer
num_electrodes: 11 # how many electrodes were recorded on
power_on_track_threshold: -75 # the minimum power on the frequency track of a window in dB to be allowed to enter the classifier
# blacklist_vertical_noise_bands: True # whether to blacklist vertical noise bands
vertical_noise_band_upper_freq_limit: 400 # vertical noise bands are evaluated below this frequency in Hz
vertical_noise_band_time_padding: 0.2 # how much time padding to add to the vertical noise band in s
vertical_noise_band_power_threshold: -80 # the minimum power of a vertical noise band in dB to be classified as a vertical noise band
min_chirp_prob: 0.65 # minimum probability of a chirp to be classified as a chirp